name: demo_ppt

on: 
  schedule:
    - cron: '*/15 * * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - name: Set Timezone to +7 (With input)
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Ho_Chi_Minh"
        timezoneMacos: "Asia/Ho_Chi_Minh"
        timezoneWindows: "Asia/Ho_Chi_Minh"
    - name: Set up Python 3.9.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.13
    - name: send email
      run: |
        python main.py ${{ secrets.GMAIL_USER }} ${{ secrets.GMAIL_PWD }} ${{ secrets.GMAIL_RECIPIENT }} 